### PR TITLE
Generating an initial changelog, using git extras

### PR DESCRIPTION
**Pull request by matzew**
Adding a changelog file, generated using `git changelog` from [git extras](https://github.com/tj/git-extras)

### CODE REVIEW

**Comment by maleck13** [comment]
Would it be useful to have short git hash beside each of the lines, so if you wanted to go back and look at what was done for change X it would be easy to do from this file?

**Comment by matzew** [comment]
@maleck13 I think I will try this one: https://github.com/conventional-changelog/standard-version 

suggested by @wei-lee

**Comment by matzew** [comment]
example _CHANGELOG_:   https://github.com/conventional-changelog/standard-version/blob/master/CHANGELOG.md

**Comment by matzew** [comment]
@maleck13 for now, I think that's the best / most easy we can get

**Comment by matzew** [comment]
@maleck13 how about this:

https://gist.github.com/matzew/87b9c515d0aa26d1999551b1c1adecc2

**Comment by maleck13** [comment]
+1 looks ok to me

**Pull request merged**
